### ISSUE TITLE
Apple collision not working correctly

### ISSUE THREAD

**Issue by hmzq-dev** [OskarProgrammer/SnakePygame#1]
While playing the game I noticed that only the snake's x position has to be aligned with the apple's x position in order for it be counted as eaten. This may be because in the `app.check_point` function:
```
    def check_point(self):
        for x in range(0,10):
            if self.__position_point.x+x == self.__position_play.x:
                self.__score += self.__add
                self.__GAINED = True
                return

        for x in range(0,10):
            if self.__position_point.y+x == self.__position_play.y:
                self.__score += self.__add
                self.__GAINED = True
                return
```
If the first `for` loop detects that the x positions of the snake and apple are colliding, it returns and thus exits the function, which is why the second `for` loop doesnt run (and so its never checked whether or not the y positions of the snake and apple are colliding).

**Comment by OskarProgrammer** [comment]
There is one issue with that, I made snake game in console already and there I was referencing to the coordinates of a two-dimensional array, that was easy to make. 
This project is my first project in pygame and i have got one question about it. Is there any module in this library (pygame library), which allow me to detect if the object got collision with another object? Because I don't really believe that I have to manually code it.

**Comment by hamza-qadir0** [comment]
You're right. There are many ways to check for a collision in pygame. You could either make rectangle objects for the snake and points instead of circles, and use the `one_rect.colliderect(second_rect)` method that returns True if their is a collision. 

Alternatively, you could make sprite objects and use masks for pixel perfect collision using [this link](https://stackoverflow.com/questions/27642234/pygame-circle-collision). 

Let me know if you need any more help.

**Comment by OskarProgrammer** [comment]
Done! Thank you so much. I hope this looks clean. Apple and snake finally got good lines for collision. If you have got any advice or tips about  code deployment in my project, write me. 

In main loop:
`try:
                self.point()
                self.check_point()
            except:
                pass
`

How self.check_point looks:

`def check_point(self): 
        if self.__player_rect.colliderect(self.__point_rect):
            self.__score += self.__add
            self.__GAINED = True
        else:
            pass
`

PS: How can I put code in comments on github?

**Comment by hmzq-404** [comment]
Code can be shown in comments on github between two backticks (  `   ) and multi line code should be between three backticks (```). 

Some suggestions:

1. I dont think you need the `try except` statement inline 47 and the `else` statement in line 98. 
2. Maybe not put the `while` loop in the `__init__()` method, and instead make another method like `App.loop()` and call this method after `Snake = App()` because it looks more readable.
3. The screen closes way too soon after the snake dies. I made some changes to the while loop so that the window only closes when the user clicks on the 'X' button:
```
        while True:
            # Quits pygame if 'X' button is pressed
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()

            self.background()
            self.player()
            self.movement(self.__direction)

            self.__key = pygame.key.get_pressed()
            self.event_handling(self.__key)

            self.score_tab()

            if self.__GAINED:
                self.__position_point = pygame.Vector2(random.randint(50,self.__screen.get_height()-20),random.randint(50,self.__screen.get_height()-20))

                if random.randint(0,2)==0:
                    self.__color = "red"
                    self.__add = 1
                elif random.randint(0,2)==1:
                    self.__color = "purple"
                    self.__add = 2
                else:
                    self.__color = "orange"
                    self.__add = 3

                self.__GAINED = False
            
            self.point()
            self.check_point()

            # If the snake is dead, this runs every frame and thus draws the score screen over the game
            if self.check_lose():
                self.end()
                self.__score = 0

            pygame.display.flip()
            self.fps()
```
I changed the while loop to always run, even when the snake is dead, and so you dont `App.__RUNNING` or `App.exit()`

Other than that, keep making projects like these!

**Comment by hamza-qadir0** [comment]
Code can be shown in comments on github between two backticks (  `   ) and multi line code should be between three backticks (```). 

Some suggestions:

1. As a challenge, make the snake grow by 1 square everytime it eats a point / apple
2. I dont think you need the `try except` statement inline 47 and the `else` statement in line 98. 
3. Maybe not put the `while` loop in the `__init__()` method, and instead make another method like `App.loop()` and call this method after `Snake = App()` because it looks more readable.
4. The screen closes way too soon after the snake dies. I made some changes to the while loop so that the window only closes when the user clicks on the 'X' button:
```
        while True:
            # Quits pygame if 'X' button is pressed
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()

            self.background()
            self.player()
            self.movement(self.__direction)

            self.__key = pygame.key.get_pressed()
            self.event_handling(self.__key)

            self.score_tab()

            if self.__GAINED:
                self.__position_point = pygame.Vector2(random.randint(50,self.__screen.get_height()-20),random.randint(50,self.__screen.get_height()-20))

                if random.randint(0,2)==0:
                    self.__color = "red"
                    self.__add = 1
                elif random.randint(0,2)==1:
                    self.__color = "purple"
                    self.__add = 2
                else:
                    self.__color = "orange"
                    self.__add = 3

                self.__GAINED = False
            
            self.point()
            self.check_point()

            # If the snake is dead, this runs every frame and thus draws the score screen over the game
            if self.check_lose():
                self.end()
                self.__score = 0

            pygame.display.flip()
            self.fps()
```
I changed the while loop to always run, even when the snake is dead, and so you dont `App.__RUNNING` or `App.exit()`

Other than that, keep making projects like this!
